package animals;

import java.util.Random;

public enum DogBreed {
	
	BULLDOG,
	POODLE,
	BEAGLE,
	BOXER,
	GOLDENRETRIEVER,
	CHIHUAHUA,
	GERMANSHEPERD,
	DACHSHUND,
	LABRETRIEVER,
	BORDERCOLLIE,
	ROTTWEILER,
	DALMATIAN;
	
	/**
	 * Randomly generates a dog breed from the enum DogBreed, which contains a list of possible dog breeds for the Dog Class.
	 * @return The DogBreed variable at the random index generated by the Random() function
	 */
	public static DogBreed getRandomDogBreed() {
		Random random = new Random();
		return values()[random.nextInt(values().length)];
	}
	
}
