package animals;

import java.util.Random;

public enum FurType {
	
	LONGHAIR,
	MEDIUMHAIR,
	SHORTHAIR,
	CURLY,
	SILKY,
	WIRY,
	SMOOTH,
	HAIRLESS;
	
	/**
	 * Randomly generates a fur type from the enum FurType, which contains a list of possible fur types for the Animal Class.
	 * @return The FurType variable at the random index generated by the Random() function
	 */
	public static FurType getRandomFurType() {
		Random random = new Random();
		return values()[random.nextInt(values().length)];
	}
	
}
